image:
  name: ocaml/opam:debian-12-ocaml-5.1  
  pull_policy: always                    

stages: [check, test]

variables:
  OPAMYES: "true"

cache:
  key: opam-cache
  paths:
    - /home/opam/.opam
    - fp/_build

.default:
  before_script:
    - opam update
    - opam install dune alcotest qcheck qcheck-alcotest ocamlformat
    - cd fp

format:
  stage: check
  extends: .default
  script:
    - FILES="$(git ls-files '*.ml' '*.mli' || true)"
    - if [ -n "$FILES" ]; then ocamlformat --check $FILES; else echo "No OCaml files"; fi

lint:
  stage: check
  extends: .default
  script:
    - dune build @all

test:
  stage: test
  extends: .default
  script:
    - dune runtest --no-buffer
