stages: [format, build, test]

default:
  tags: [wsl-shell]

variables:
  OPAMYES: "true"

before_script:
  - eval $(opam env)
  - opam update
  - opam switch show || opam switch create 5.2.1
  - opam install -y dune ocamlformat.0.26.2 alcotest

format:
  stage: format
  script:
    - FILES="$(git ls-files '*.ml' '*.mli')"
    - if [ -n "$FILES" ]; then ocamlformat --check $FILES; fi

build:
  stage: build
  script:
    - dune build @all
  artifacts: { when: always, paths: [ _build/log ] }

test:
  stage: test
  script:
    - dune runtest --no-buffer
  artifacts: { when: always, paths: [ _build/_tests ] }
