stages:
  - check
  - test

.check-template:
  tags: [wsl-shell]
  before_script:
    - eval $(opam env)  

format:
  stage: check
  extends: .check-template
  script:
    - FILES="$(git ls-files '*.ml' '*.mli')"
    - if [ -n "$FILES" ]; then ocamlformat --check $FILES; fi

lint:
  stage: check
  extends: .check-template
  script:
    - dune build @all     

test:
  stage: test
  extends: .check-template
  script:
    - dune runtest --no-buffer
