# лучше этот тег: он точнее и обычно есть
image: ocaml/opam:ubuntu-22.04-ocaml-5.2

stages: [format, build, test]

variables:
  OPAMYES: "true"
  DOCKER_IMAGE_PULL_POLICY: "always"   # переопределяем политику pull

before_script:
  - opam update
  - opam switch show
  - opam install dune ocamlformat.0.26.2 alcotest

format:
  stage: format
  script:
    - FILES="$(git ls-files '*.ml' '*.mli')"
    - if [ -n "$FILES" ]; then ocamlformat --check $FILES; fi

build:
  stage: build
  script:
    - dune build @all
  artifacts: { when: always, paths: [ _build/log ] }

test:
  stage: test
  script:
    - dune runtest --no-buffer
  artifacts: { when: always, paths: [ _build/_tests ] }
