stages: [check, test]

variables:
  GIT_STRATEGY: clone  
  GIT_DEPTH: 0         

.root-template:
  tags: [wsl-shell]
  before_script:
    - eval $(opam env)

.fp-template:
  tags: [wsl-shell]
  before_script:
    - eval $(opam env)
    - cd fp

format:
  stage: check
  extends: .root-template
  script:
    - FILES="$(git ls-files 'fp/**/*.ml' 'fp/**/*.mli' || true)"
    - |
      if [ -n "$FILES" ]; then
        ocamlformat --check $FILES
      else
        echo "No OCaml files"
      fi

lint:
  stage: check
  extends: .fp-template
  script:
    - dune build @all

test:
  stage: test
  extends: .fp-template
  script:
    - dune runtest --no-buffer
