stages: [check, test]

default:
  before_script:
    - rm -rf $CI_PROJECT_DIR/*
    - git fetch --unshallow || true


.check-template:
  tags: [wsl-shell]
  before_script:
    - eval $(opam env)
    - cd fp

format:
  stage: check
  tags: [wsl-shell]
  before_script:
    - eval $(opam env)
  script:
    - FILES="$(git ls-files 'fp/**/*.ml' 'fp/**/*.mli' || true)"
    - if [ -n "$FILES" ]; then ocamlformat --check $FILES; fi

lint:
  stage: check
  extends: .check-template
  script:
    - dune build @all

test:
  stage: test
  extends: .check-template
  script:
    - dune runtest --no-buffer
